### ISSUE TITLE
Cannot send XTZ with Trezor model T, firmware 2.3.0

### ISSUE THREAD

**Issue by detony** [simplestaking/wallet#16]
Hello,
I cannot send XTZ with the SimpleStaking web wallet. Instead of confirming transaction, Trezor asks me to write my passphrase again. If I write it and confirm it, the following message comes :
"Warning : TrezorConnect: TezosSignTransaction. error: Device call in progress. "

Screen of the issue : https://www.reddit.com/r/TREZOR/comments/ge5co9/simplestaking_cannot_send_tezos_230_firmware/

**Comment by jurajselep** [comment]
Hello, 

this issue is related to trezor-bridge:  
https://github.com/trezor/trezord-go/issues/154

Fixed by using workaround from: 
https://github.com/trezor/connect/pull/561
